POST localhost:5000/users/signup
Content-Type: application/json

{
   "firstName":"samuel",
   "lastName":"samju",
    "email":"samju77770@gmail.com",
    "password":"samju100",
    "confirmPassword":"samju100",
    "location":"lagos"
}
