POST  localhost:5000/users/signin
Content-Type: application/json

{
   "firstName":"samuel",
   "lastName":"samju",
    "email":"samju70@gmail.com",
    "password":"samju100",
    "confirmPassword":"samju100",
    "location":"lagos"
}
